package org.antinori.astar;



import java.util.EventListener;

/**
* The listener interface for receiving events related to paths generated by a {@link PathFinder}.
*
* @author Gene McCulley
*/
public interface PathListener<T extends Node> extends EventListener {

 /**
  * Called when a new path is being considered.
  *
  * @param e the PathEvent that belongs to the PathFinder.
  */
 void considered(PathEvent<T> e);

}

