package org.antinori.game;

import static org.antinori.game.Card.green;
import static org.antinori.game.Card.mustard;
import static org.antinori.game.Card.peacock;
import static org.antinori.game.Card.plum;
import static org.antinori.game.Card.scarlet;
import static org.antinori.game.Card.white;
import static org.antinori.game.Player.COLOR_GREEN;
import static org.antinori.game.Player.COLOR_MUSTARD;
import static org.antinori.game.Player.COLOR_PEACOCK;
import static org.antinori.game.Player.COLOR_PLUM;
import static org.antinori.game.Player.COLOR_SCARLET;
import static org.antinori.game.Player.COLOR_WHITE;

public class SinglePlayerSelectionDialog2 extends javax.swing.JDialog {

    public SinglePlayerSelectionDialog2(java.awt.Frame parent, boolean modal) {

        super(parent, modal);
        ClueMain.setLocationInCenter(this, -400, -300);

        setUndecorated(true);

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        bg = new javax.swing.JPanel();
        fgPanel = new javax.swing.JPanel();
        peacockCheckbox = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        mustardCheckbox = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        greenCheckbox = new javax.swing.JCheckBox();
        okButton = new javax.swing.JButton();
        nameLabel = new javax.swing.JLabel();
        scarletCheckbox = new javax.swing.JCheckBox();
        whiteRadio = new javax.swing.JRadioButton();
        playerNameTextField = new javax.swing.JTextField();
        plumLabel = new javax.swing.JLabel();
        mustardRadio = new javax.swing.JRadioButton();
        plumCheckbox = new javax.swing.JCheckBox();
        scarletRadio = new javax.swing.JRadioButton();
        whiteCheckbox = new javax.swing.JCheckBox();
        mustardLabel = new javax.swing.JLabel();
        peacockLabel = new javax.swing.JLabel();
        scarletLabel = new javax.swing.JLabel();
        plumRadio = new javax.swing.JRadioButton();
        peacockRadio = new javax.swing.JRadioButton();
        greenRadio = new javax.swing.JRadioButton();
        greenLabel = new javax.swing.JLabel();
        whiteLabel = new javax.swing.JLabel();
        bgLabel = new javax.swing.JLabel();

        difficulty_group = new javax.swing.ButtonGroup();
        easy_rb = new javax.swing.JRadioButton();
        hard_rb = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();

        playerRadioGroup = new javax.swing.ButtonGroup();
        playerRadioGroup.add(scarletRadio);
        playerRadioGroup.add(mustardRadio);
        playerRadioGroup.add(plumRadio);
        playerRadioGroup.add(greenRadio);
        playerRadioGroup.add(whiteRadio);
        playerRadioGroup.add(peacockRadio);

        bg.setMinimumSize(new java.awt.Dimension(1, 1));
        bg.setLayout(new java.awt.GridBagLayout());

        fgPanel.setOpaque(false);
        fgPanel.setPreferredSize(new java.awt.Dimension(600, 500));

        bgLabel.setIcon(ClueMain.getImageIcon("frame1.png")); // NOI18N

        scarletLabel.setIcon(ClueMain.getImageIcon("MsScarlett.png")); // NOI18N

        whiteLabel.setIcon(ClueMain.getImageIcon("MrsWhite.png")); // NOI18N

        greenLabel.setIcon(ClueMain.getImageIcon("MrGreen.png")); // NOI18N

        peacockLabel.setIcon(ClueMain.getImageIcon("MrsPeacock.png")); // NOI18N

        plumLabel.setIcon(ClueMain.getImageIcon("ProfPlum.png")); // NOI18N

        mustardLabel.setIcon(ClueMain.getImageIcon("ColMustard.png")); // NOI18N

        nameLabel.setText("Player Name");

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        jLabel1.setText("Select at least 2 computer players");

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        jLabel2.setText("Select your character and enter your name");

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        whiteRadio.setText("Mrs. White");
        whiteRadio.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                whiteRadioItemStateChanged(evt);
            }
        });

        mustardRadio.setText("Colonel Mustard");
        mustardRadio.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                mustardRadioItemStateChanged(evt);
            }
        });

        scarletRadio.setSelected(true);

        scarletRadio.setText("Miss Scarlet");
        scarletRadio.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                scarletRadioItemStateChanged(evt);
            }
        });

        plumRadio.setText("Professor Plum");
        plumRadio.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                plumRadioItemStateChanged(evt);
            }
        });

        peacockRadio.setText("Mrs. Peacock");
        peacockRadio.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                peacockRadioItemStateChanged(evt);
            }
        });

        greenRadio.setText("Mr. Green");
        greenRadio.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                greenRadioItemStateChanged(evt);
            }
        });

        mustardCheckbox.setSelected(true);
        mustardCheckbox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                mustardCheckboxItemStateChanged(evt);
            }
        });

        peacockCheckbox.setSelected(true);
        peacockCheckbox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                peacockCheckboxItemStateChanged(evt);
            }
        });

        greenCheckbox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                greenCheckboxItemStateChanged(evt);
            }
        });

        scarletCheckbox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                scarletCheckboxItemStateChanged(evt);
            }
        });

        plumCheckbox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                plumCheckboxItemStateChanged(evt);
            }
        });

        scarletRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scarletRadioActionPerformed(evt);
            }
        });

        whiteCheckbox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                whiteCheckboxItemStateChanged(evt);
            }
        });

        playerNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playerNameTextFieldActionPerformed(evt);
            }
        });

        difficulty_group.add(easy_rb);
        easy_rb.setSelected(true);
        easy_rb.setText("easy");

        difficulty_group.add(hard_rb);
        hard_rb.setText("expert");

        jLabel3.setText("Select Difficulty Level");

        org.jdesktop.layout.GroupLayout fgPanelLayout = new org.jdesktop.layout.GroupLayout(fgPanel);
        fgPanel.setLayout(fgPanelLayout);
        fgPanelLayout.setHorizontalGroup(
                fgPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(fgPanelLayout.createSequentialGroup()
                                .add(153, 153, 153)
                                .add(fgPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                        .add(fgPanelLayout.createSequentialGroup()
                                                .add(fgPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                                        .add(fgPanelLayout.createSequentialGroup()
                                                                .add(fgPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                                                        .add(scarletRadio)
                                                                        .add(greenRadio)
                                                                        .add(whiteRadio))
                                                                .add(67, 67, 67)
                                                                .add(fgPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                                                        .add(peacockRadio)
                                                                        .add(plumRadio)
                                                                        .add(mustardRadio)))
                                                        .add(fgPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                                                .add(jLabel2)
                                                                .add(org.jdesktop.layout.GroupLayout.LEADING, fgPanelLayout.createSequentialGroup()
                                                                        .add(fgPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                                                                .add(playerNameTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 138, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                                                .add(nameLabel))
                                                                        .add(32, 32, 32)
                                                                        .add(fgPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                                                                .add(jLabel3)
                                                                                .add(fgPanelLayout.createSequentialGroup()
                                                                                        .add(easy_rb)
                                                                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                                                                        .add(hard_rb))))))
                                                .addContainerGap())
                                        .add(org.jdesktop.layout.GroupLayout.TRAILING, fgPanelLayout.createSequentialGroup()
                                                .add(fgPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                                        .add(fgPanelLayout.createSequentialGroup()
                                                                .add(0, 0, Short.MAX_VALUE)
                                                                .add(okButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 87, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                                        .add(fgPanelLayout.createSequentialGroup()
                                                                .add(fgPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                                                                        .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel1)
                                                                        .add(fgPanelLayout.createSequentialGroup()
                                                                                .add(fgPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                                                                        .add(scarletLabel)
                                                                                        .add(peacockLabel)
                                                                                        .add(peacockCheckbox)
                                                                                        .add(scarletCheckbox))
                                                                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                .add(fgPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                                                                        .add(mustardCheckbox)
                                                                                        .add(whiteCheckbox)
                                                                                        .add(whiteLabel)
                                                                                        .add(mustardLabel))))
                                                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 66, Short.MAX_VALUE)
                                                                .add(fgPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                                                        .add(plumLabel)
                                                                        .add(plumCheckbox)
                                                                        .add(greenLabel)
                                                                        .add(greenCheckbox))))
                                                .add(101, 101, 101))))
        );
        fgPanelLayout.setVerticalGroup(
                fgPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(fgPanelLayout.createSequentialGroup()
                                .add(29, 29, 29)
                                .add(jLabel2)
                                .add(4, 4, 4)
                                .add(fgPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                        .add(scarletRadio)
                                        .add(plumRadio))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(fgPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                        .add(greenRadio)
                                        .add(peacockRadio))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(fgPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                        .add(whiteRadio)
                                        .add(mustardRadio))
                                .add(18, 18, 18)
                                .add(fgPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                        .add(nameLabel)
                                        .add(jLabel3))
                                .add(6, 6, 6)
                                .add(fgPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                        .add(playerNameTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(easy_rb)
                                        .add(hard_rb))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 15, Short.MAX_VALUE)
                                .add(jLabel1)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(fgPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                        .add(fgPanelLayout.createSequentialGroup()
                                                .add(fgPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                                        .add(fgPanelLayout.createSequentialGroup()
                                                                .add(greenLabel)
                                                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                                                .add(greenCheckbox))
                                                        .add(fgPanelLayout.createSequentialGroup()
                                                                .add(113, 113, 113)
                                                                .add(plumLabel)
                                                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                                                .add(plumCheckbox)))
                                                .add(18, 18, 18)
                                                .add(okButton))
                                        .add(fgPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                                .add(fgPanelLayout.createSequentialGroup()
                                                        .add(scarletLabel)
                                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                                        .add(scarletCheckbox)
                                                        .add(10, 10, 10)
                                                        .add(peacockLabel)
                                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                                        .add(peacockCheckbox))
                                                .add(org.jdesktop.layout.GroupLayout.TRAILING, fgPanelLayout.createSequentialGroup()
                                                        .add(mustardLabel)
                                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                                        .add(mustardCheckbox)
                                                        .add(10, 10, 10)
                                                        .add(whiteLabel)
                                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                                        .add(whiteCheckbox))))
                                .add(27, 27, 27))
        );

        bg.add(fgPanel, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        bg.add(bgLabel, gridBagConstraints);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(bg, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(bg, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void scarletRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scarletRadioActionPerformed
        setCheckboxes();
    }//GEN-LAST:event_scarletRadioActionPerformed

    private void peacockCheckboxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_peacockCheckboxItemStateChanged
        setCheckboxes();

    }//GEN-LAST:event_peacockCheckboxItemStateChanged

    private void whiteCheckboxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_whiteCheckboxItemStateChanged
        setCheckboxes();

    }//GEN-LAST:event_whiteCheckboxItemStateChanged

    private void plumCheckboxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_plumCheckboxItemStateChanged
        setCheckboxes();

    }//GEN-LAST:event_plumCheckboxItemStateChanged

    private void greenCheckboxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_greenCheckboxItemStateChanged
        setCheckboxes();

    }//GEN-LAST:event_greenCheckboxItemStateChanged

    private void mustardCheckboxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_mustardCheckboxItemStateChanged
        setCheckboxes();

    }//GEN-LAST:event_mustardCheckboxItemStateChanged

    private void scarletCheckboxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_scarletCheckboxItemStateChanged
        setCheckboxes();

    }//GEN-LAST:event_scarletCheckboxItemStateChanged

    private void scarletRadioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_scarletRadioItemStateChanged
        setCheckboxes();

    }//GEN-LAST:event_scarletRadioItemStateChanged

    private void greenRadioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_greenRadioItemStateChanged
        setCheckboxes();

    }//GEN-LAST:event_greenRadioItemStateChanged

    private void whiteRadioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_whiteRadioItemStateChanged
        setCheckboxes();

    }//GEN-LAST:event_whiteRadioItemStateChanged

    private void mustardRadioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_mustardRadioInputMethodTextChanged
        setCheckboxes();

    }//GEN-LAST:event_mustardRadioInputMethodTextChanged

    private void plumRadioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_plumRadioItemStateChanged
        setCheckboxes();

    }//GEN-LAST:event_plumRadioItemStateChanged

    private void peacockRadioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_peacockRadioItemStateChanged
        setCheckboxes();

    }//GEN-LAST:event_peacockRadioItemStateChanged

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed

        int count = 0;
        if (scarletCheckbox.isSelected()) {
            count++;
        }
        if (greenCheckbox.isSelected()) {
            count++;
        }
        if (mustardCheckbox.isSelected()) {
            count++;
        }
        if (plumCheckbox.isSelected()) {
            count++;
        }
        if (peacockCheckbox.isSelected()) {
            count++;
        }
        if (whiteCheckbox.isSelected()) {
            count++;
        }

        if (count < 2) {
            return;
        }

        //main player
        if (scarletRadio.isSelected()) {
            ClueMain.clue.addPlayer(scarlet, playerNameTextField.getText(), COLOR_SCARLET, false);
        }
        if (greenRadio.isSelected()) {
            ClueMain.clue.addPlayer(green, playerNameTextField.getText(), COLOR_GREEN, false);
        }
        if (mustardRadio.isSelected()) {
            ClueMain.clue.addPlayer(mustard, playerNameTextField.getText(), COLOR_MUSTARD, false);
        }
        if (plumRadio.isSelected()) {
            ClueMain.clue.addPlayer(plum, playerNameTextField.getText(), COLOR_PLUM, false);
        }
        if (peacockRadio.isSelected()) {
            ClueMain.clue.addPlayer(peacock, playerNameTextField.getText(), COLOR_PEACOCK, false);
        }
        if (whiteRadio.isSelected()) {
            ClueMain.clue.addPlayer(white, playerNameTextField.getText(), COLOR_WHITE, false);
        }

        //computer players
        if (scarletCheckbox.isSelected()) {
            ClueMain.clue.addPlayer(scarlet, "", COLOR_SCARLET, true);
        }
        if (greenCheckbox.isSelected()) {
            ClueMain.clue.addPlayer(green, "", COLOR_GREEN, true);
        }
        if (mustardCheckbox.isSelected()) {
            ClueMain.clue.addPlayer(mustard, "", COLOR_MUSTARD, true);
        }
        if (plumCheckbox.isSelected()) {
            ClueMain.clue.addPlayer(plum, "", COLOR_PLUM, true);
        }
        if (peacockCheckbox.isSelected()) {
            ClueMain.clue.addPlayer(peacock, "", COLOR_PEACOCK, true);
        }
        if (whiteCheckbox.isSelected()) {
            ClueMain.clue.addPlayer(white, "", COLOR_WHITE, true);
        }

        if (hard_rb.isSelected()) {
            ClueMain.difficult_setting = true;
        }

        dispose();

    }//GEN-LAST:event_okButtonActionPerformed

    private void playerNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playerNameTextFieldActionPerformed

    }//GEN-LAST:event_playerNameTextFieldActionPerformed

    private void setCheckboxes() {
        if (scarletRadio.isSelected()) {
            scarletCheckbox.setSelected(false);
        }
        if (mustardRadio.isSelected()) {
            mustardCheckbox.setSelected(false);
        }
        if (whiteRadio.isSelected()) {
            whiteCheckbox.setSelected(false);
        }
        if (plumRadio.isSelected()) {
            plumCheckbox.setSelected(false);
        }
        if (peacockRadio.isSelected()) {
            peacockCheckbox.setSelected(false);
        }
        if (greenRadio.isSelected()) {
            greenCheckbox.setSelected(false);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JLabel bgLabel;
    private javax.swing.JPanel fgPanel;
    private javax.swing.JCheckBox greenCheckbox;
    private javax.swing.JLabel greenLabel;
    private javax.swing.JRadioButton greenRadio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JCheckBox mustardCheckbox;
    private javax.swing.JLabel mustardLabel;
    private javax.swing.JRadioButton mustardRadio;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JButton okButton;
    private javax.swing.JCheckBox peacockCheckbox;
    private javax.swing.JLabel peacockLabel;
    private javax.swing.JRadioButton peacockRadio;
    private javax.swing.JTextField playerNameTextField;
    private javax.swing.JCheckBox plumCheckbox;
    private javax.swing.JLabel plumLabel;
    private javax.swing.JRadioButton plumRadio;
    private javax.swing.JCheckBox scarletCheckbox;
    private javax.swing.JLabel scarletLabel;
    private javax.swing.JRadioButton scarletRadio;
    private javax.swing.JCheckBox whiteCheckbox;
    private javax.swing.JLabel whiteLabel;
    private javax.swing.JRadioButton whiteRadio;

    private javax.swing.ButtonGroup playerRadioGroup;

    private javax.swing.ButtonGroup difficulty_group;
    private javax.swing.JRadioButton easy_rb;
    private javax.swing.JRadioButton hard_rb;
    private javax.swing.JLabel jLabel3;

    // End of variables declaration//GEN-END:variables
}
